[package]
name = "metadata-generator"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.98"
# TODO: Eventually remove quick-xml, is it less nice to use.
quick-xml = "0.38.1"
rayon = "1.11.0"
roxmltree = "0.20.0"
regex = "1.11.1"
